language: php
php:
  - 5.3
  - 5.4
env:
  - REDIS_STANDALONE=0
  - REDIS_STANDALONE=1
before_script:
  - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then pecl install redis && echo \"extension=redis.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`; fi"
  - composer install --dev